#!/bin/bash

export PYTHONPATH=/spin/software/python_pkg/astroid/1.6.4/python/2.7/linux/64/astroid:/spin/software/python_pkg/pylint/1.8.1/python/2.7/linux/64:/spin/software/python_pkg/lazy-object-proxy/1.3.1/python/2.7/linux/64:/spin/software/python_pkg/singledispatch/3.4.0.3/python/2.7/linux/64:/spin/software/python_pkg/backports.functools_lru_cache/1.4/python/2.7/linux/64:/spin/software/python_pkg/wrapt/1.10.11/python/2.7/linux/64:/spin/software/python_pkg/configparser/3.5.0/python/2.7/linux/64:/spin/software/python_pkg/isort/4.2.15/python/2.7/linux/64:$PYTHONPATH

# FIXME: expects to be in package root:
/spin/software/python_pkg/pylint/1.8.1/python/2.7/linux/64/EGG-INFO/scripts/pylint "$@"
